name: people_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_map: ^6.0.1
  flutter_riverpod: ^2.4.5
  latlong2: ^0.9.0
  riverpod: ^2.4.5
  shimmer: ^3.0.0
  url_launcher: ^6.2.1

flutter:
  uses-material-design: true


